use_frameworks!

target 'ScrollController_Example' do
    pod 'ScrollController', :path => '../'
    pod 'SnapKit'

    target 'ScrollController_Tests' do
        inherit! :search_paths
    end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
