use_frameworks!

target 'SlideController_Example' do
    pod 'SlideController', :path => '../'
    
    target 'SlideController_Tests' do
        inherit! :search_paths
    end
end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'SlideController'
            target.build_configurations.each do |config|
                if config.name == 'Debug'
                    config.build_settings['OTHER_SWIFT_FLAGS'] = '-D DEVELOPMENT'
                    else
                    config.build_settings['OTHER_SWIFT_FLAGS'] = ''
                end
            end
        end
    end
end
